import { StyleSheet } from 'react-native';
import { palette } from '../../styles/theme/theme';

export default StyleSheet.create({
  anatomy: {
    paddingVertical: 48,
    backgroundColor: palette.ink,
  },
  anatomyInner: { gap: 36 },
  anatomyWide: { gap: 54, alignItems: `center`, flexDirection: `row` },
  anatomyColumn: { flex: 1, minWidth: 0 },
  plate: { padding: 20, borderWidth: 1, borderColor: palette.muted, backgroundColor: palette.steel },
  plateLabel: { fontSize: 14, letterSpacing: 2, color: palette.muted, textTransform: `uppercase`, fontFamily: `DragonSlapper` },
  plateArtwork: { width: `100%`, aspectRatio: 5 / 3, marginVertical: 18 },
  plateCaption: { fontSize: 18, lineHeight: 24, paddingTop: 14, borderTopWidth: 1, borderColor: palette.muted, color: palette.ink, fontFamily: `DragonSlapper` },
  eyebrow: { fontSize: 13, lineHeight: 19, marginBottom: 16, letterSpacing: 2, color: palette.muted, textTransform: `uppercase`, fontFamily: `DragonSlapper` },
  darkEyebrow: { color: palette.steel },
  heading: { fontSize: 30, lineHeight: 39, color: palette.ink, fontFamily: `DragonSlapper` },
  wideHeading: { fontSize: 42, lineHeight: 54 },
  lightHeading: { color: palette.paper },
  anatomyNotes: { marginTop: 26 },
  anatomyNote: { gap: 16, paddingVertical: 21, borderTopWidth: 1, borderColor: palette.muted, flexDirection: `row` },
  noteNumber: { minWidth: 26, fontSize: 14, lineHeight: 25, color: palette.steel, fontFamily: `DragonSlapper` },
  noteBody: { flex: 1, minWidth: 0 },
  noteTitle: { fontSize: 22, lineHeight: 29, marginBottom: 10, color: palette.ink, fontFamily: `DragonSlapper` },
  noteText: { fontSize: 21, lineHeight: 30, color: palette.muted, fontFamily: `AlegreyaSans` },
  darkNoteText: { color: palette.steel },
  lore: { paddingVertical: 48 },
  loreGrid: { gap: 32, marginTop: 30 },
  loreWide: { gap: 54, flexDirection: `row` },
  loreColumn: { flex: 1, minWidth: 0 },
  loreNote: { paddingTop: 26, borderTopWidth: 1, borderColor: palette.line },
  loreNumber: { fontSize: 28, lineHeight: 36, marginBottom: 22, color: palette.red, fontFamily: `DragonSlapper` },
  invitation: { paddingVertical: 48, backgroundColor: palette.ink },
  invitationPanel: { padding: 28, borderWidth: 1, borderColor: palette.line, overflow: `hidden`, alignItems: `center`, backgroundColor: palette.steel },
  invitationArtwork: { ...StyleSheet.absoluteFillObject },
  invitationSword: { width: `88%`, maxWidth: 340, height: 36, marginBottom: 26 },
  centered: { textAlign: `center` },
  invitationCopy: { fontSize: 21, lineHeight: 30, maxWidth: 560, marginTop: 22, color: palette.ink, textAlign: `center`, fontFamily: `AlegreyaSans` },
  actions: { gap: 14, width: `100%`, marginTop: 28 },
  wideActions: { width: `auto`, flexDirection: `row`, justifyContent: `center` },
  link: { gap: 10, minHeight: 48, paddingVertical: 14, paddingHorizontal: 20, borderWidth: 1, borderColor: palette.steel, flexDirection: `row`, alignItems: `center`, justifyContent: `center` },
  primaryLink: { borderColor: palette.steel, backgroundColor: palette.ink },
  linkLabel: { fontSize: 20, lineHeight: 26, color: palette.ink, fontFamily: `DragonSlapper` },
  primaryLabel: { color: palette.paper },
  pressed: { opacity: .72 },
});
